version: "3.8"

services:
   node:
      container_name: togo_manabie_server
      build:
         context: .
         dockerfile: ./Dockerfile
      restart: on-failure
      ports:
         - ${PORT}:${PORT}
      environment:
         - PORT=${PORT}
         - DATABASE_URL=${DATABASE_URL}
      volumes:
         - .:/togo-manabie
      command: yarn start
