name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Install package
        run: npm ci
      - name: Check code format 
        run: npm run lint
      - name: Run test
        run: npm run test:coverage